// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MarketChartsColumns holds the columns for the "market_charts" table.
	MarketChartsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "currency", Type: field.TypeString},
		{Name: "chart", Type: field.TypeJSON},
	}
	// MarketChartsTable holds the schema information for the "market_charts" table.
	MarketChartsTable = &schema.Table{
		Name:       "market_charts",
		Columns:    MarketChartsColumns,
		PrimaryKey: []*schema.Column{MarketChartsColumns[0]},
	}
	// MarketsColumns holds the columns for the "markets" table.
	MarketsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "markets", Type: field.TypeJSON},
		{Name: "time", Type: field.TypeTime},
	}
	// MarketsTable holds the schema information for the "markets" table.
	MarketsTable = &schema.Table{
		Name:       "markets",
		Columns:    MarketsColumns,
		PrimaryKey: []*schema.Column{MarketsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MarketChartsTable,
		MarketsTable,
	}
)

func init() {
}
