// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MarketsColumns holds the columns for the "markets" table.
	MarketsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "markets", Type: field.TypeJSON},
		{Name: "time", Type: field.TypeTime},
	}
	// MarketsTable holds the schema information for the "markets" table.
	MarketsTable = &schema.Table{
		Name:       "markets",
		Columns:    MarketsColumns,
		PrimaryKey: []*schema.Column{MarketsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MarketsTable,
	}
)

func init() {
}
