// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/manasky/cryptomeme/internal/ent/migrate"

	"github.com/manasky/cryptomeme/internal/ent/marketchart"
	"github.com/manasky/cryptomeme/internal/ent/markets"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// MarketChart is the client for interacting with the MarketChart builders.
	MarketChart *MarketChartClient
	// Markets is the client for interacting with the Markets builders.
	Markets *MarketsClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.MarketChart = NewMarketChartClient(c.config)
	c.Markets = NewMarketsClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		MarketChart: NewMarketChartClient(cfg),
		Markets:     NewMarketsClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:      cfg,
		MarketChart: NewMarketChartClient(cfg),
		Markets:     NewMarketsClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		MarketChart.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.MarketChart.Use(hooks...)
	c.Markets.Use(hooks...)
}

// MarketChartClient is a client for the MarketChart schema.
type MarketChartClient struct {
	config
}

// NewMarketChartClient returns a client for the MarketChart from the given config.
func NewMarketChartClient(c config) *MarketChartClient {
	return &MarketChartClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `marketchart.Hooks(f(g(h())))`.
func (c *MarketChartClient) Use(hooks ...Hook) {
	c.hooks.MarketChart = append(c.hooks.MarketChart, hooks...)
}

// Create returns a create builder for MarketChart.
func (c *MarketChartClient) Create() *MarketChartCreate {
	mutation := newMarketChartMutation(c.config, OpCreate)
	return &MarketChartCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MarketChart entities.
func (c *MarketChartClient) CreateBulk(builders ...*MarketChartCreate) *MarketChartCreateBulk {
	return &MarketChartCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MarketChart.
func (c *MarketChartClient) Update() *MarketChartUpdate {
	mutation := newMarketChartMutation(c.config, OpUpdate)
	return &MarketChartUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MarketChartClient) UpdateOne(mc *MarketChart) *MarketChartUpdateOne {
	mutation := newMarketChartMutation(c.config, OpUpdateOne, withMarketChart(mc))
	return &MarketChartUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MarketChartClient) UpdateOneID(id uuid.UUID) *MarketChartUpdateOne {
	mutation := newMarketChartMutation(c.config, OpUpdateOne, withMarketChartID(id))
	return &MarketChartUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MarketChart.
func (c *MarketChartClient) Delete() *MarketChartDelete {
	mutation := newMarketChartMutation(c.config, OpDelete)
	return &MarketChartDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *MarketChartClient) DeleteOne(mc *MarketChart) *MarketChartDeleteOne {
	return c.DeleteOneID(mc.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *MarketChartClient) DeleteOneID(id uuid.UUID) *MarketChartDeleteOne {
	builder := c.Delete().Where(marketchart.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MarketChartDeleteOne{builder}
}

// Query returns a query builder for MarketChart.
func (c *MarketChartClient) Query() *MarketChartQuery {
	return &MarketChartQuery{
		config: c.config,
	}
}

// Get returns a MarketChart entity by its id.
func (c *MarketChartClient) Get(ctx context.Context, id uuid.UUID) (*MarketChart, error) {
	return c.Query().Where(marketchart.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MarketChartClient) GetX(ctx context.Context, id uuid.UUID) *MarketChart {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MarketChartClient) Hooks() []Hook {
	return c.hooks.MarketChart
}

// MarketsClient is a client for the Markets schema.
type MarketsClient struct {
	config
}

// NewMarketsClient returns a client for the Markets from the given config.
func NewMarketsClient(c config) *MarketsClient {
	return &MarketsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `markets.Hooks(f(g(h())))`.
func (c *MarketsClient) Use(hooks ...Hook) {
	c.hooks.Markets = append(c.hooks.Markets, hooks...)
}

// Create returns a create builder for Markets.
func (c *MarketsClient) Create() *MarketsCreate {
	mutation := newMarketsMutation(c.config, OpCreate)
	return &MarketsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Markets entities.
func (c *MarketsClient) CreateBulk(builders ...*MarketsCreate) *MarketsCreateBulk {
	return &MarketsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Markets.
func (c *MarketsClient) Update() *MarketsUpdate {
	mutation := newMarketsMutation(c.config, OpUpdate)
	return &MarketsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MarketsClient) UpdateOne(m *Markets) *MarketsUpdateOne {
	mutation := newMarketsMutation(c.config, OpUpdateOne, withMarkets(m))
	return &MarketsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MarketsClient) UpdateOneID(id uuid.UUID) *MarketsUpdateOne {
	mutation := newMarketsMutation(c.config, OpUpdateOne, withMarketsID(id))
	return &MarketsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Markets.
func (c *MarketsClient) Delete() *MarketsDelete {
	mutation := newMarketsMutation(c.config, OpDelete)
	return &MarketsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *MarketsClient) DeleteOne(m *Markets) *MarketsDeleteOne {
	return c.DeleteOneID(m.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *MarketsClient) DeleteOneID(id uuid.UUID) *MarketsDeleteOne {
	builder := c.Delete().Where(markets.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MarketsDeleteOne{builder}
}

// Query returns a query builder for Markets.
func (c *MarketsClient) Query() *MarketsQuery {
	return &MarketsQuery{
		config: c.config,
	}
}

// Get returns a Markets entity by its id.
func (c *MarketsClient) Get(ctx context.Context, id uuid.UUID) (*Markets, error) {
	return c.Query().Where(markets.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MarketsClient) GetX(ctx context.Context, id uuid.UUID) *Markets {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MarketsClient) Hooks() []Hook {
	return c.hooks.Markets
}
