// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/manasky/cryptomeme/common"
	"github.com/manasky/cryptomeme/internal/ent/marketchart"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MarketChartCreate is the builder for creating a MarketChart entity.
type MarketChartCreate struct {
	config
	mutation *MarketChartMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (mcc *MarketChartCreate) SetCreateTime(t time.Time) *MarketChartCreate {
	mcc.mutation.SetCreateTime(t)
	return mcc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (mcc *MarketChartCreate) SetNillableCreateTime(t *time.Time) *MarketChartCreate {
	if t != nil {
		mcc.SetCreateTime(*t)
	}
	return mcc
}

// SetUpdateTime sets the "update_time" field.
func (mcc *MarketChartCreate) SetUpdateTime(t time.Time) *MarketChartCreate {
	mcc.mutation.SetUpdateTime(t)
	return mcc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (mcc *MarketChartCreate) SetNillableUpdateTime(t *time.Time) *MarketChartCreate {
	if t != nil {
		mcc.SetUpdateTime(*t)
	}
	return mcc
}

// SetName sets the "name" field.
func (mcc *MarketChartCreate) SetName(s string) *MarketChartCreate {
	mcc.mutation.SetName(s)
	return mcc
}

// SetCurrency sets the "currency" field.
func (mcc *MarketChartCreate) SetCurrency(s string) *MarketChartCreate {
	mcc.mutation.SetCurrency(s)
	return mcc
}

// SetChart sets the "chart" field.
func (mcc *MarketChartCreate) SetChart(cc common.MarketChart) *MarketChartCreate {
	mcc.mutation.SetChart(cc)
	return mcc
}

// SetID sets the "id" field.
func (mcc *MarketChartCreate) SetID(u uuid.UUID) *MarketChartCreate {
	mcc.mutation.SetID(u)
	return mcc
}

// Mutation returns the MarketChartMutation object of the builder.
func (mcc *MarketChartCreate) Mutation() *MarketChartMutation {
	return mcc.mutation
}

// Save creates the MarketChart in the database.
func (mcc *MarketChartCreate) Save(ctx context.Context) (*MarketChart, error) {
	var (
		err  error
		node *MarketChart
	)
	mcc.defaults()
	if len(mcc.hooks) == 0 {
		if err = mcc.check(); err != nil {
			return nil, err
		}
		node, err = mcc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MarketChartMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mcc.check(); err != nil {
				return nil, err
			}
			mcc.mutation = mutation
			if node, err = mcc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(mcc.hooks) - 1; i >= 0; i-- {
			if mcc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mcc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mcc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mcc *MarketChartCreate) SaveX(ctx context.Context) *MarketChart {
	v, err := mcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcc *MarketChartCreate) Exec(ctx context.Context) error {
	_, err := mcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcc *MarketChartCreate) ExecX(ctx context.Context) {
	if err := mcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mcc *MarketChartCreate) defaults() {
	if _, ok := mcc.mutation.CreateTime(); !ok {
		v := marketchart.DefaultCreateTime()
		mcc.mutation.SetCreateTime(v)
	}
	if _, ok := mcc.mutation.UpdateTime(); !ok {
		v := marketchart.DefaultUpdateTime()
		mcc.mutation.SetUpdateTime(v)
	}
	if _, ok := mcc.mutation.ID(); !ok {
		v := marketchart.DefaultID()
		mcc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mcc *MarketChartCreate) check() error {
	if _, ok := mcc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "create_time"`)}
	}
	if _, ok := mcc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "update_time"`)}
	}
	if _, ok := mcc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "name"`)}
	}
	if _, ok := mcc.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "currency"`)}
	}
	if _, ok := mcc.mutation.Chart(); !ok {
		return &ValidationError{Name: "chart", err: errors.New(`ent: missing required field "chart"`)}
	}
	return nil
}

func (mcc *MarketChartCreate) sqlSave(ctx context.Context) (*MarketChart, error) {
	_node, _spec := mcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		_node.ID = _spec.ID.Value.(uuid.UUID)
	}
	return _node, nil
}

func (mcc *MarketChartCreate) createSpec() (*MarketChart, *sqlgraph.CreateSpec) {
	var (
		_node = &MarketChart{config: mcc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: marketchart.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: marketchart.FieldID,
			},
		}
	)
	if id, ok := mcc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := mcc.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: marketchart.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := mcc.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: marketchart.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if value, ok := mcc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: marketchart.FieldName,
		})
		_node.Name = value
	}
	if value, ok := mcc.mutation.Currency(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: marketchart.FieldCurrency,
		})
		_node.Currency = value
	}
	if value, ok := mcc.mutation.Chart(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: marketchart.FieldChart,
		})
		_node.Chart = value
	}
	return _node, _spec
}

// MarketChartCreateBulk is the builder for creating many MarketChart entities in bulk.
type MarketChartCreateBulk struct {
	config
	builders []*MarketChartCreate
}

// Save creates the MarketChart entities in the database.
func (mccb *MarketChartCreateBulk) Save(ctx context.Context) ([]*MarketChart, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mccb.builders))
	nodes := make([]*MarketChart, len(mccb.builders))
	mutators := make([]Mutator, len(mccb.builders))
	for i := range mccb.builders {
		func(i int, root context.Context) {
			builder := mccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MarketChartMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mccb *MarketChartCreateBulk) SaveX(ctx context.Context) []*MarketChart {
	v, err := mccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mccb *MarketChartCreateBulk) Exec(ctx context.Context) error {
	_, err := mccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mccb *MarketChartCreateBulk) ExecX(ctx context.Context) {
	if err := mccb.Exec(ctx); err != nil {
		panic(err)
	}
}
