// Code generated by entc, DO NOT EDIT.

package ent

import (
	"cryptolist/internal/ent/marketchart"
	"cryptolist/internal/ent/markets"
	"cryptolist/internal/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	marketchartMixin := schema.MarketChart{}.Mixin()
	marketchartMixinFields0 := marketchartMixin[0].Fields()
	_ = marketchartMixinFields0
	marketchartFields := schema.MarketChart{}.Fields()
	_ = marketchartFields
	// marketchartDescCreateTime is the schema descriptor for create_time field.
	marketchartDescCreateTime := marketchartMixinFields0[0].Descriptor()
	// marketchart.DefaultCreateTime holds the default value on creation for the create_time field.
	marketchart.DefaultCreateTime = marketchartDescCreateTime.Default.(func() time.Time)
	// marketchartDescUpdateTime is the schema descriptor for update_time field.
	marketchartDescUpdateTime := marketchartMixinFields0[1].Descriptor()
	// marketchart.DefaultUpdateTime holds the default value on creation for the update_time field.
	marketchart.DefaultUpdateTime = marketchartDescUpdateTime.Default.(func() time.Time)
	// marketchart.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	marketchart.UpdateDefaultUpdateTime = marketchartDescUpdateTime.UpdateDefault.(func() time.Time)
	// marketchartDescID is the schema descriptor for id field.
	marketchartDescID := marketchartFields[0].Descriptor()
	// marketchart.DefaultID holds the default value on creation for the id field.
	marketchart.DefaultID = marketchartDescID.Default.(func() uuid.UUID)
	marketsMixin := schema.Markets{}.Mixin()
	marketsMixinFields0 := marketsMixin[0].Fields()
	_ = marketsMixinFields0
	marketsFields := schema.Markets{}.Fields()
	_ = marketsFields
	// marketsDescCreateTime is the schema descriptor for create_time field.
	marketsDescCreateTime := marketsMixinFields0[0].Descriptor()
	// markets.DefaultCreateTime holds the default value on creation for the create_time field.
	markets.DefaultCreateTime = marketsDescCreateTime.Default.(func() time.Time)
	// marketsDescUpdateTime is the schema descriptor for update_time field.
	marketsDescUpdateTime := marketsMixinFields0[1].Descriptor()
	// markets.DefaultUpdateTime holds the default value on creation for the update_time field.
	markets.DefaultUpdateTime = marketsDescUpdateTime.Default.(func() time.Time)
	// markets.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	markets.UpdateDefaultUpdateTime = marketsDescUpdateTime.UpdateDefault.(func() time.Time)
	// marketsDescID is the schema descriptor for id field.
	marketsDescID := marketsFields[0].Descriptor()
	// markets.DefaultID holds the default value on creation for the id field.
	markets.DefaultID = marketsDescID.Default.(func() uuid.UUID)
}
