name: Deploy yo Github Pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Install
        run: cd web && npm install
        
      - name: build
        run: |
          cd web
          VITE_API_PATH='https://api.cryptomeme.wtf/v1' npm run build
          touch public/.nojekyll
          touch public/test.md
          cp public/index.html public/404.html
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/public
          cname: cryptomeme.wtf


